Repository tqec/tqec, pull requests merged in 2024-08, with the labels that each got.

#283 Implement qubit borders template
  src/tqec/templates/constructions/qubit.py
Labels: enhancement, backend, needs-review

#279 Introduce temporal `ComputationBlock`
  src/tqec/block/block.py
  src/tqec/block/enums.py
  src/tqec/block/library/closed.py
  src/tqec/block/library/open.py
  src/tqec/circuit/circuit.py
  src/tqec/circuit/circuit_test.py
  src/tqec/circuit/operations/operation.py
  src/tqec/circuit/schedule.py
  src/tqec/plaquette/library/empty_test.py
  src/tqec/plaquette/library/initialisation.py
  src/tqec/plaquette/library/initialisation_test.py
  src/tqec/plaquette/library/measurement.py
  src/tqec/plaquette/library/measurement_test.py
  src/tqec/plaquette/library/memory.py
  src/tqec/plaquette/library/memory_test.py
  src/tqec/plaquette/library/pauli.py
  src/tqec/plaquette/library/utils/schedule.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/qubit.py
  src/tqec/plaquette/qubit_test.py
  src/tqec/templates/constructions/qubit.py
  src/tqec/templates/constructions/qubit_test.py
Labels: enhancement, backend, needs-review

#290 Find correlation subgraphs with `ZXGraph` and visualize them
  notebooks/sketchup_demo.ipynb
  src/tqec/sketchup/block_graph.py
  src/tqec/sketchup/zx_graph.py
Labels: enhancement, backend, needs-review

#293 Merge duplicated data-structure
  src/tqec/block/block.py
  src/tqec/position.py
Labels: enhancement, backend, refactor, QOL

#296 Introduce `AbstractObservable` that represents the location of measurements that should be included in a observable.
  notebooks/sketchup_demo.ipynb
  src/tqec/sketchup/block_graph.py
Labels: enhancement, backend, needs-review

#300 Add a CLI to list found observables
  pyproject.toml
  src/tqec/_cli/dae2observables.py
  src/tqec/sketchup/zx_graph.py
Labels: enhancement, backend, QOL

#303 Improve CI and include coverage data
  .github/workflows/ci.yml
  pyproject.toml
Labels: enhancement, backend, ci/cd
