Repository tqec/tqec, pull requests merged in 2024-10, with the labels that each got.

#322 Improve documentation for installation / quick start
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .github/workflows/pr-close.yml
  .gitignore
  README.md
  docs/_static/media/quick_start/cnot_sketchup.html
  docs/_templates/autosummary/module.rst
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  docs/installation.rst
  docs/media/detectors/detector_computation_illustration.ipynb
  docs/media/quick_start/clean_exportable_cnot.dae
  docs/media/quick_start/clean_exportable_cnot.stim
  docs/quick_start.rst
  notebooks/move_qubit_along_a_line.ipynb
  src/tqec/compile/block.py
  src/tqec/sketchup/block_graph.py
Labels: documentation, backend

#326 Removing frontend v1
  .github/workflows/ci.yml
  frontend/.eslintrc.json
  frontend/.gcloudignore
  frontend/.gitignore
  frontend/README.md
  frontend/app.yaml
  frontend/deploy.sh
  frontend/dispatch.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/__tests__/App.test.js
  frontend/src/__tests__/setupTests.js
  frontend/src/actions.js
  frontend/src/components/Button.js
  frontend/src/components/download/DownloadButton.js
  frontend/src/components/download/config.js
  frontend/src/components/notification.js
  frontend/src/control-flow.js
  frontend/src/graphics/Grid.js
  frontend/src/graphics/GridUnit.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/plaquettes/AsciiCircuitWriter.js
  frontend/src/plaquettes/Footprint.js
  frontend/src/plaquettes/Plaquette.js
  frontend/src/plaquettes/StimCircuitWriter.js
  frontend/src/qubits/Qubit.js
  frontend/src/qubits/QubitLabels.js
  frontend/src/qubits/QubitLattice.js
  frontend/src/reducers.js
  frontend/src/store.js
  web/.gcloudignore
  web/app.yaml
  web/deploy-gcloud.sh
  web/deploy-local.sh
  web/main.py
  web/static/index.html
Labels: enhancement, frontend, QOL

#327 Removing FUNDING.yml file
  .github/FUNDING.yml
Labels: documentation, enhancement

#329 Adding benchmarks using topological CNOT generation
  examples/benchmarks/bench.sh
  examples/benchmarks/cnot_all_observables.py
  pyproject.toml
Labels: enhancement, backend

#332 Simulate bigger (up to `k = 5`) logical CNOT
  assets/logical_cnot_result.png
  examples/logical_cnot.py
Labels: documentation, backend

#339 Remove unused code from `tqec.templates`
  src/tqec/__init__.py
  src/tqec/circuit/measurement.py
  src/tqec/circuit/measurement_test.py
  src/tqec/compile/block.py
  src/tqec/compile/compile.py
  src/tqec/compile/observables.py
  src/tqec/compile/specs.py
  src/tqec/interval.py
  src/tqec/interval_test.py
  src/tqec/plaquette/plaquette.py
  src/tqec/scale.py
  src/tqec/scale_test.py
  src/tqec/templates/__init__.py
  src/tqec/templates/_testing.py
  src/tqec/templates/_testing_test.py
  src/tqec/templates/base.py
  src/tqec/templates/grid.py
  src/tqec/templates/interval.py
  src/tqec/templates/layout.py
  src/tqec/templates/qubit.py
  src/tqec/templates/qubit_test.py
Labels: enhancement, backend

#338 Introduce a few helpers in `tqec.simulation`
  examples/logical_cnot.py
  pyproject.toml
  src/tqec/_cli/subcommands/dae2observables.py
  src/tqec/simulation/__init__.py
  src/tqec/simulation/generation.py
  src/tqec/simulation/plotting/__init__.py
  src/tqec/simulation/plotting/inset.py
  src/tqec/simulation/simulation.py
  src/tqec/sketchup/zx_graph.py
Labels: enhancement, backend

#341 `plaquette.library` is now using `RX`/`MX` instead of `H` gates
  src/tqec/circuit/observable_qubits_test.py
  src/tqec/plaquette/library/initialisation.py
  src/tqec/plaquette/library/initialisation_test.py
  src/tqec/plaquette/library/measurement.py
  src/tqec/plaquette/library/measurement_test.py
  src/tqec/plaquette/library/memory.py
  src/tqec/plaquette/library/memory_test.py
  src/tqec/plaquette/library/pauli.py
  src/tqec/plaquette/library/utils/schedule.py
Labels: enhancement, backend

#340 Refactor `tqec.sketchup`
  benchmarks/cnot_all_observables.py
  src/tqec/__init__.py
  src/tqec/_cli/subcommands/check_dae.py
  src/tqec/_cli/subcommands/dae2circuits.py
  src/tqec/_cli/subcommands/dae2observables.py
  src/tqec/compile/compile.py
  src/tqec/compile/observables.py
  src/tqec/compile/specs.py
  src/tqec/compile/substitute.py
  src/tqec/computation/__init__.py
  src/tqec/computation/block_graph/__init__.py
  src/tqec/computation/block_graph/color.py
  src/tqec/computation/block_graph/cube.py
  src/tqec/computation/block_graph/enums.py
  src/tqec/computation/block_graph/graph.py
  src/tqec/computation/block_graph/graph_test.py
  src/tqec/computation/block_graph/observable.py
  src/tqec/computation/block_graph/pipe.py
  src/tqec/computation/collada.py
  src/tqec/computation/collada_test.py
  src/tqec/computation/geometry.py
  src/tqec/computation/plot.py
  src/tqec/computation/zx_graph.py
  src/tqec/computation/zx_graph_test.py
  src/tqec/simulation/plotting/inset.py
  src/tqec/simulation/simulation.py
Labels: enhancement, backend, refactor

#343 Avoid storing `k` in `Template` instances
  src/tqec/circuit/generation.py
  src/tqec/circuit/generation_test.py
  src/tqec/circuit/observable_qubits.py
  src/tqec/circuit/observable_qubits_test.py
  src/tqec/compile/block.py
  src/tqec/compile/compile.py
  src/tqec/compile/observables.py
  src/tqec/templates/_testing.py
  src/tqec/templates/_testing_test.py
  src/tqec/templates/base.py
  src/tqec/templates/display.py
  src/tqec/templates/layout.py
  src/tqec/templates/qubit.py
  src/tqec/templates/qubit_test.py
Labels: enhancement, backend, refactor

#342 Refactor plaquette library
  src/tqec/__init__.py
  src/tqec/circuit/generation.py
  src/tqec/circuit/generation_test.py
  src/tqec/circuit/moment.py
  src/tqec/circuit/observable_qubits_test.py
  src/tqec/circuit/schedule.py
  src/tqec/circuit/schedule_test.py
  src/tqec/compile/specs.py
  src/tqec/compile/substitute.py
  src/tqec/computation/block_graph/graph.py
  src/tqec/plaquette/__init__.py
  src/tqec/plaquette/enums.py
  src/tqec/plaquette/library/__init__.py
  src/tqec/plaquette/library/css.py
  src/tqec/plaquette/library/css_test.py
  src/tqec/plaquette/library/empty.py
  src/tqec/plaquette/library/empty_test.py
  src/tqec/plaquette/library/initialisation.py
  src/tqec/plaquette/library/initialisation_test.py
  src/tqec/plaquette/library/measurement.py
  src/tqec/plaquette/library/measurement_test.py
  src/tqec/plaquette/library/memory.py
  src/tqec/plaquette/library/memory_test.py
  src/tqec/plaquette/library/pauli.py
  src/tqec/plaquette/library/utils/schedule.py
  src/tqec/plaquette/library/zxxz.py
  src/tqec/plaquette/library/zxxz_test.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/qubit.py
  src/tqec/plaquette/qubit_test.py
Labels: bug, enhancement, backend, refactor

#344 Introduce a `QubitMap` structure
  src/tqec/circuit/qubit.py
  src/tqec/circuit/qubit_map.py
  src/tqec/circuit/qubit_map_test.py
  src/tqec/circuit/qubit_test.py
  src/tqec/circuit/schedule.py
  src/tqec/circuit/schedule_test.py
  src/tqec/plaquette/library/css.py
  src/tqec/plaquette/library/zxxz.py
Labels: enhancement, backend

#345 Various fixes for logical CNOT using `ZXXZ` code
  benchmarks/cnot_all_observables.py
  examples/logical_cnot.py
  src/tqec/_cli/subcommands/dae2circuits.py
  src/tqec/circuit/detectors/match.py
  src/tqec/compile/__init__.py
  src/tqec/compile/compile.py
  src/tqec/compile/specs.py
  src/tqec/compile/specs/__init__.py
  src/tqec/compile/specs/base.py
  src/tqec/compile/specs/enums.py
  src/tqec/compile/specs/library/__init__.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/compile/specs/library/css.py
  src/tqec/compile/specs/library/zxxz.py
  src/tqec/compile/substitute.py
  src/tqec/plaquette/plaquette.py
  src/tqec/simulation/simulation.py
Labels: bug, enhancement, backend

#350 Introduce `DetectorDatabase` and needed helpers
  src/tqec/circuit/detectors/boundary.py
  src/tqec/circuit/detectors/match.py
  src/tqec/circuit/generation.py
  src/tqec/circuit/generation_test.py
  src/tqec/circuit/instructions.py
  src/tqec/circuit/measurement.py
  src/tqec/circuit/measurement_map.py
  src/tqec/circuit/measurement_map_test.py
  src/tqec/circuit/measurement_test.py
  src/tqec/circuit/moment.py
  src/tqec/circuit/moment_test.py
  src/tqec/circuit/qubit.py
  src/tqec/circuit/qubit_map.py
  src/tqec/circuit/qubit_map_test.py
  src/tqec/circuit/qubit_test.py
  src/tqec/circuit/schedule.py
  src/tqec/circuit/schedule_test.py
  src/tqec/compile/block.py
  src/tqec/compile/compile.py
  src/tqec/compile/detectors/compute.py
  src/tqec/compile/detectors/database.py
  src/tqec/compile/detectors/detector.py
  src/tqec/compile/detectors/detector_test.py
  src/tqec/compile/observables.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/compile/substitute.py
  src/tqec/plaquette/frozendefaultdict.py
  src/tqec/plaquette/library/css.py
  src/tqec/plaquette/library/zxxz.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/qubit.py
  src/tqec/templates/subtemplates.py
Labels: enhancement, backend

#362 Pipe as plaquettes
  README.md
  benchmarks/cnot_all_observables.py
  docs/quick_start.rst
  examples/logical_cnot.py
  src/tqec/_cli/subcommands/dae2circuits.py
  src/tqec/circuit/generation_test.py
  src/tqec/compile/__init__.py
  src/tqec/compile/block.py
  src/tqec/compile/compile.py
  src/tqec/compile/compile_test.py
  src/tqec/compile/observables.py
  src/tqec/compile/specs/__init__.py
  src/tqec/compile/specs/base.py
  src/tqec/compile/specs/library/__init__.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/compile/specs/library/css.py
  src/tqec/compile/specs/library/zxxz.py
  src/tqec/compile/substitute.py
  src/tqec/computation/block_graph/cube.py
  src/tqec/computation/block_graph/enums.py
  src/tqec/computation/block_graph/graph.py
  src/tqec/computation/block_graph/pipe.py
  src/tqec/gallery/__init__.py
  src/tqec/gallery/logical_cnot.py
  src/tqec/plaquette/library/__init__.py
  src/tqec/plaquette/library/builder.py
  src/tqec/plaquette/library/css.py
  src/tqec/plaquette/library/css_test.py
  src/tqec/plaquette/library/zxxz.py
  src/tqec/plaquette/library/zxxz_test.py
  src/tqec/plaquette/plaquette.py
  src/tqec/simulation/simulation.py
  src/tqec/templates/_testing.py
  src/tqec/templates/base.py
  src/tqec/templates/enums.py
  src/tqec/templates/layout.py
  src/tqec/templates/qubit.py
  src/tqec/templates/qubit_test.py
Labels: enhancement, backend, QOL

#365 Require `python<3.13` and add `typing-extensions` to requirements
  requirements.txt
Labels: bug, backend

#372 Adding `StimCoordinates`
  src/tqec/circuit/coordinates.py
  src/tqec/circuit/coordinates_test.py
  src/tqec/circuit/qubit.py
  src/tqec/compile/detectors/compute.py
  src/tqec/compile/detectors/detector.py
  src/tqec/compile/detectors/detector_test.py
Labels: enhancement, backend

#371 Add name to `Plaquette`
  src/tqec/plaquette/library/css.py
  src/tqec/plaquette/library/css_test.py
  src/tqec/plaquette/library/empty.py
  src/tqec/plaquette/library/zxxz.py
  src/tqec/plaquette/library/zxxz_test.py
  src/tqec/plaquette/plaquette.py
Labels: enhancement, backend

#376 `DetectorDatabase` is now implemented with a translation-invariant key system
  src/tqec/compile/detectors/database.py
  src/tqec/compile/detectors/database_test.py
  src/tqec/plaquette/frozendefaultdict.py
  src/tqec/plaquette/plaquette.py
Labels: enhancement, backend, database
