Repository tqec/tqec, pull requests merged in 2024-02, with the labels that each got.

#99 Using corner pinning in ScalableCorner
  src/tqec/templates/constructions/corner.py
Labels: enhancement, backend

#73 Replace assertions in the code
  src/tqec/detectors/gate.py
  src/tqec/detectors/measurement_map.py
  src/tqec/detectors/transformer.py
  src/tqec/exceptions.py
  src/tqec/generation/circuit.py
  src/tqec/noise_models/idle_qubits.py
  src/tqec/plaquette/schedule.py
  src/tqec/templates/base.py
  src/tqec/templates/orchestrator.py
  src/tqec/templates/scalable/rectangle.py
  src/tqec/templates/scalable/square.py
  src/tqec/templates/shapes/base.py
  src/tqec/templates/shapes/rectangle.py
  src/tqec/templates/shapes/square.py
Labels: documentation, backend

#97 Update `tqec.templates.constructions` classes to the new scale definition `k`
  notebooks/corner.ipynb
  notebooks/logical_qubit_extended_memory_experiment.ipynb
  notebooks/logical_qubit_memory_experiment.ipynb
  src/tqec/templates/constructions/corner.py
  src/tqec/templates/constructions/qubit.py
Labels: enhancement, backend

#124 Add support for Python 3.9
  src/tqec/detectors/measurement_map.py
  src/tqec/detectors/operation.py
  src/tqec/detectors/transformer.py
  src/tqec/display.py
  src/tqec/generation/circuit.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/schedule.py
  src/tqec/templates/base.py
  src/tqec/templates/constructions/qubit.py
  src/tqec/templates/scalable/rectangle.py
Labels: documentation, backend, ci/cd

#128 Fix CircuitMeasurementMap not adhering to the documented API
  src/tqec/detectors/measurement_map.py
Labels: bug, backend

#114 Tentative at removing BaseShape
  notebooks/corner.ipynb
  notebooks/doubling_distance.ipynb
  notebooks/logical_qubit_extended_memory_experiment.ipynb
  notebooks/logical_qubit_memory_experiment.ipynb
  notebooks/move_qubit_along_a_line.ipynb
  src/tqec/generation/circuit_test.py
  src/tqec/templates/atomic/rectangle.py
  src/tqec/templates/atomic/rectangle_test.py
  src/tqec/templates/atomic/square.py
  src/tqec/templates/atomic/square_test.py
  src/tqec/templates/base.py
  src/tqec/templates/composed.py
  src/tqec/templates/constructions/corner.py
  src/tqec/templates/constructions/qubit.py
  src/tqec/templates/fixed/base.py
  src/tqec/templates/fixed/rectangle.py
  src/tqec/templates/fixed/square.py
  src/tqec/templates/scalable/base.py
  src/tqec/templates/scalable/rectangle.py
  src/tqec/templates/scalable/square.py
  src/tqec/templates/scale.py
  src/tqec/templates/scale_test.py
  src/tqec/templates/shapes/base.py
  src/tqec/templates/shapes/rectangle.py
  src/tqec/templates/shapes/square.py
Labels: backend, refactor

#133 Add redux; update package.json and eslintrc
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.js
Labels: enhancement, frontend, refactor

#119 Add customizable qubit constellation
  frontend/src/workspace/PlanarVector.js
  frontend/src/workspace/components/button.js
  frontend/src/workspace/components/download/DownloadButton.js
  frontend/src/workspace/components/download/config.js
  frontend/src/workspace/components/notification.js
  frontend/src/workspace/graphics/BoundingBox.js
  frontend/src/workspace/graphics/Grid.js
  frontend/src/workspace/graphics/GridUnit.js
  frontend/src/workspace/grid.js
  frontend/src/workspace/index.js
  frontend/src/workspace/plaquettes/Plaquette.js
  frontend/src/workspace/plaquettes/Template.js
  frontend/src/workspace/qubits/Qubit.js
  frontend/src/workspace/qubits/QubitLattice.js
  package-lock.json
Labels: frontend, task-1

#121 CI
  .github/workflows/ci.yml
  frontend/src/__tests__/App.test.js
  frontend/src/__tests__/setupTests.js
  frontend/tests/App.test.js
  frontend/tests/setupTests.js
  src/tqec/generation/circuit_test.py
Labels: ci/cd

#145 Add feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ci/cd

#155 Fix `AlternatingCornerSquareTemplate`
  src/tqec/__init__.py
  src/tqec/templates/__init__.py
  src/tqec/templates/atomic/__init__.py
  src/tqec/templates/atomic/square.py
  src/tqec/templates/constructions/__init__.py
Labels: bug, backend

#137 Refactor Plaquette hierarchy
  notebooks/logical_qubit_extended_memory_experiment.ipynb
  notebooks/logical_qubit_memory_experiment.ipynb
  notebooks/move_qubit_along_a_line.ipynb
  src/tqec/__init__.py
  src/tqec/detectors/measurement_map.py
  src/tqec/detectors/operation.py
  src/tqec/enums.py
  src/tqec/generation/circuit_test.py
  src/tqec/plaquette/__init__.py
  src/tqec/plaquette/library/__init__.py
  src/tqec/plaquette/library/empty.py
  src/tqec/plaquette/library/initialisation.py
  src/tqec/plaquette/library/measurement.py
  src/tqec/plaquette/library/utils/detectors.py
  src/tqec/plaquette/library/utils/pauli.py
  src/tqec/plaquette/library/xx.py
  src/tqec/plaquette/library/xxxx.py
  src/tqec/plaquette/library/zz.py
  src/tqec/plaquette/library/zzzz.py
  src/tqec/plaquette/plaquette.py
  src/tqec/templates/atomic/rectangle.py
  src/tqec/templates/atomic/square.py
  src/tqec/templates/base.py
Labels: enhancement, backend, refactor, needs-review

#163 Re-organise backend file structure
  src/tqec/__init__.py
  src/tqec/circuit/__init__.py
  src/tqec/circuit/circuit.py
  src/tqec/circuit/circuit_test.py
  src/tqec/circuit/operations/__init__.py
  src/tqec/circuit/operations/measurement_map.py
  src/tqec/circuit/operations/operation.py
  src/tqec/circuit/operations/transformer.py
  src/tqec/circuit/schedule.py
  src/tqec/generation/__init__.py
  src/tqec/generation/topology.py
  src/tqec/non_template_scaling/__init__.py
  src/tqec/non_template_scaling/animated_shape_display.py
  src/tqec/non_template_scaling/display_data.py
  src/tqec/non_template_scaling/non_template_scaling.py
  src/tqec/plaquette/__init__.py
  src/tqec/plaquette/library/empty.py
  src/tqec/plaquette/library/initialisation.py
  src/tqec/plaquette/library/measurement.py
  src/tqec/plaquette/library/utils/detectors.py
  src/tqec/plaquette/library/xx.py
  src/tqec/plaquette/library/xxxx.py
  src/tqec/plaquette/library/zz.py
  src/tqec/plaquette/library/zzzz.py
  src/tqec/plaquette/plaquette.py
  src/tqec/templates/__init__.py
  src/tqec/templates/display.py
Labels: enhancement, help wanted, backend, refactor

#165 Fix linter warnings F401
  ruff.toml
Labels: backend
