Repository tqec/tqec, pull requests merged in 2024-11, with the labels that each got.

#380 Refactor `tqec.circuit.schedule` into submodules
  .pre-commit-config.yaml
  src/tqec/circuit/schedule/__init__.py
  src/tqec/circuit/schedule/circuit.py
  src/tqec/circuit/schedule/circuit_test.py
  src/tqec/circuit/schedule/exception.py
  src/tqec/circuit/schedule/manipulation.py
  src/tqec/circuit/schedule/manipulation_test.py
  src/tqec/circuit/schedule/schedule.py
  src/tqec/circuit/schedule/schedule_test.py
Labels: enhancement, backend, refactor

#393 Use PyData sphinx docs theme
  docs/_static/media/quick_start/logical_cnot.html
  docs/api.rst
  docs/conf.py
  docs/contributor_guide.rst
  docs/index.rst
  docs/user_guide/detectors.rst
  docs/user_guide/index.rst
  docs/user_guide/installation.rst
  docs/user_guide/quick_start.rst
  pyproject.toml
  requirements-dev.txt
  src/tqec/circuit/__init__.py
  src/tqec/circuit/coordinates.py
  src/tqec/circuit/instructions.py
  src/tqec/circuit/measurement_map.py
  src/tqec/circuit/qubit_map.py
  src/tqec/circuit/schedule/circuit.py
  src/tqec/compile/detectors/compute.py
  src/tqec/compile/detectors/database.py
  src/tqec/compile/detectors/detector.py
  src/tqec/plaquette/library/__init__.py
  src/tqec/plaquette/library/zxxz.py
  src/tqec/plaquette/plaquette.py
  src/tqec/simulation/plotting/__init__.py
  src/tqec/simulation/plotting/inset.py
Labels: documentation, enhancement, backend

#405 Stricter typing
  pyproject.toml
  src/tqec/__init__.py
  src/tqec/_cli/subcommands/dae2observables.py
  src/tqec/circuit/__init__.py
  src/tqec/circuit/detectors/construction.py
  src/tqec/circuit/detectors/construction_test.py
  src/tqec/circuit/detectors/fragment.py
  src/tqec/circuit/detectors/match.py
  src/tqec/circuit/detectors/match_utils/cover_test.py
  src/tqec/circuit/detectors/match_utils/sat.py
  src/tqec/circuit/detectors/utils.py
  src/tqec/circuit/observable_qubits.py
  src/tqec/circuit/qubit_test.py
  src/tqec/circuit/schedule/manipulation.py
  src/tqec/compile/__init__.py
  src/tqec/compile/compile.py
  src/tqec/compile/detectors/compute_test.py
  src/tqec/compile/detectors/database_test.py
  src/tqec/compile/observables.py
  src/tqec/compile/specs/__init__.py
  src/tqec/compile/specs/library/__init__.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/computation/__init__.py
  src/tqec/computation/base_graph.py
  src/tqec/computation/correlation.py
  src/tqec/gallery/__init__.py
  src/tqec/gallery/logical_cnot_test.py
  src/tqec/gallery/three_cnots_test.py
  src/tqec/interop/__init__.py
  src/tqec/interop/correlation.py
  src/tqec/noise_models/__init__.py
  src/tqec/noise_models/noise_model.py
  src/tqec/plaquette/__init__.py
  src/tqec/plaquette/frozendefaultdict.py
  src/tqec/plaquette/library/__init__.py
  src/tqec/plaquette/library/empty.py
  src/tqec/plaquette/qubit.py
  src/tqec/scale.py
  src/tqec/scale_test.py
  src/tqec/templates/__init__.py
  src/tqec/templates/_testing.py
  src/tqec/templates/layout.py
Labels: enhancement, backend
