Repository tqec/tqec, pull requests merged in 2024-03, with the labels that each got.

#130 Add tests to the library
  pyproject.toml
  src/tqec/_version.py
  src/tqec/circuit/circuit.py
  src/tqec/circuit/circuit_test.py
  src/tqec/circuit/operations/measurement_map_test.py
  src/tqec/circuit/operations/operation.py
  src/tqec/circuit/operations/operation_test.py
  src/tqec/circuit/operations/transformer.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/qubit.py
  src/tqec/plaquette/qubit_test.py
  src/tqec/position.py
  src/tqec/templates/atomic/rectangle_test.py
  src/tqec/templates/base.py
  src/tqec/templates/base_test.py
  src/tqec/templates/composed.py
  src/tqec/templates/composed_test.py
  src/tqec/templates/shifted.py
  src/tqec/templates/shifted_test.py
  src/tqec/templates/stack.py
  src/tqec/templates/stack_test.py
Labels: enhancement, backend, ci/cd

#173 Decouple Plaquette and qubits
  notebooks/corner.ipynb
  notebooks/doubling_distance.ipynb
  notebooks/logical_qubit_extended_memory_experiment.ipynb
  notebooks/logical_qubit_memory_experiment.ipynb
  notebooks/move_qubit_along_a_line.ipynb
  src/tqec/__init__.py
  src/tqec/circuit/__init__.py
  src/tqec/plaquette/__init__.py
  src/tqec/plaquette/library/empty.py
  src/tqec/plaquette/library/initialisation.py
  src/tqec/plaquette/library/measurement.py
  src/tqec/plaquette/library/xx.py
  src/tqec/plaquette/library/xxxx.py
  src/tqec/plaquette/library/zz.py
  src/tqec/plaquette/library/zzzz.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/qubit.py
Labels: enhancement, backend, refactor

#175 Pauli syndrome measurement plaquette factorisation
  src/tqec/plaquette/library/pauli.py
  src/tqec/plaquette/library/xx.py
  src/tqec/plaquette/library/xxxx.py
  src/tqec/plaquette/library/zz.py
  src/tqec/plaquette/library/zzzz.py
  src/tqec/plaquette/qubit.py
Labels: enhancement, backend, refactor

#180 Canonical form circuit builder
  frontend/src/workspace/components/download/DownloadButton.js
  frontend/src/workspace/graphics/Grid.js
  frontend/src/workspace/graphics/GridUnit.js
  frontend/src/workspace/plaquettes/Circuit.js
  frontend/src/workspace/plaquettes/Plaquette.js
  frontend/src/workspace/plaquettes/Template.js
  frontend/src/workspace/plaquettes/circuit.js
  frontend/src/workspace/qubits/Qubit.js
Labels: frontend, task-2

#157 Save unit cell to Redux store
  frontend/src/App.jsx
  frontend/src/actions.js
  frontend/src/components/Button.js
  frontend/src/components/download/DownloadButton.js
  frontend/src/components/download/config.js
  frontend/src/components/notification.js
  frontend/src/control-flow.js
  frontend/src/graphics/Grid.js
  frontend/src/graphics/GridUnit.js
  frontend/src/index.js
  frontend/src/plaquettes/Plaquette.js
  frontend/src/plaquettes/Template.js
  frontend/src/plaquettes/circuit.js
  frontend/src/qubits/Qubit.js
  frontend/src/qubits/QubitLattice.js
  frontend/src/reducers.js
  frontend/src/store.js
  frontend/src/workspace/plaquettes/circuit.js
  frontend_v2/.gitignore
Labels: frontend, QOL

#187 Update README.md
  README.md
Labels: documentation

#188 Rename frontend_v2/ to tutorial/
  tutorial/Makefile
  tutorial/README.md
  tutorial/package-lock.json
  tutorial/package.json
  tutorial/public/favicon.ico
  tutorial/public/index.html
  tutorial/public/logo192.png
  tutorial/public/logo512.png
  tutorial/public/manifest.json
  tutorial/public/robots.txt
  tutorial/src/App.css
  tutorial/src/App.js
  tutorial/src/App.test.js
  tutorial/src/index.css
  tutorial/src/index.js
  tutorial/src/reportWebVitals.js
  tutorial/src/setupTests.js
  tutorial/src/tqec_logo.svg
  tutorial/src/workspace/button.js
  tutorial/src/workspace/circuit.js
  tutorial/src/workspace/grid.js
  tutorial/src/workspace/index.js
  tutorial/src/workspace/plaquette.js
  tutorial/src/workspace/position.js
  tutorial/src/workspace/qubit.js
  tutorial/src/workspace/utils.js
Labels: frontend

#185 Add circuit writer, combine A and M specification
  frontend/package-lock.json
  frontend/package.json
  frontend/src/plaquettes/CircuitWriter.js
  frontend/src/plaquettes/Plaquette.js
  frontend/src/plaquettes/circuit.js
Labels: bug, frontend

#196 New arithmetic operators on Dimension
  src/tqec/templates/scale.py
  src/tqec/templates/scale_test.py
Labels: enhancement, backend
