Repository tqec/tqec, pull requests merged in 2024-05, with the labels that each got.

#203 Functional style plaquette
  notebooks/logical_qubit_extended_memory_experiment.ipynb
  notebooks/logical_qubit_memory_experiment.ipynb
  notebooks/move_qubit_along_a_line.ipynb
  src/tqec/circuit/circuit_test.py
  src/tqec/plaquette/library/__init__.py
  src/tqec/plaquette/library/empty.py
  src/tqec/plaquette/library/initialisation.py
  src/tqec/plaquette/library/measurement.py
  src/tqec/plaquette/library/pauli.py
  src/tqec/plaquette/library/xx.py
  src/tqec/plaquette/library/xxxx.py
  src/tqec/plaquette/library/zz.py
  src/tqec/plaquette/library/zzzz.py
Labels: enhancement, backend, refactor, QOL

#211 Setup Sphinx documentation
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .gitignore
  README.md
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  pyproject.toml
  requirements-dev.txt
  src/tqec/circuit/operations/operation.py
  src/tqec/circuit/operations/transformer.py
  src/tqec/templates/base.py
Labels: documentation, enhancement, backend, ci/cd

#224 Fix typing issue in CircuitMeasurementMap
  src/tqec/circuit/operations/measurement_map.py
Labels: bug, backend

#222 Add GitHub Pages link to documentation
  README.md
  pyproject.toml
Labels: documentation

#226 [Rev. Task 2-5] Plaquette specification
  frontend/package-lock.json
  frontend/src/actions.js
  frontend/src/components/notification.js
  frontend/src/control-flow.js
  frontend/src/graphics/Grid.js
  frontend/src/plaquettes/Plaquette.js
  frontend/src/qubits/Qubit.js
  frontend/src/qubits/QubitLabels.js
  frontend/src/qubits/QubitLattice.js
  frontend/src/reducers.js
Labels: frontend, revised-task-flow
