Repository tqec/tqec, pull requests merged in 2024-12, with the labels that each got.

#415 Allow CI/CD to fail for external PRs without required permissions
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
Labels: bug, backend, ci/cd

#411 Create plaquette from RPNG string
  examples/notebooks/create_plaquette.ipynb
  src/tqec/__init__.py
  src/tqec/circuit/__init__.py
  src/tqec/plaquette/__init__.py
  src/tqec/plaquette/rapng.py
  src/tqec/plaquette/rapng_test.py
  src/tqec/plaquette/rpng.py
  src/tqec/plaquette/rpng_test.py
Labels: enhancement, backend

#421 Introduce `RPNGTemplate`
  src/tqec/__init__.py
  src/tqec/circuit/generation.py
  src/tqec/circuit/generation_test.py
  src/tqec/circuit/observable_qubits.py
  src/tqec/circuit/observable_qubits_test.py
  src/tqec/compile/block.py
  src/tqec/compile/compile.py
  src/tqec/compile/detectors/__init__.py
  src/tqec/compile/detectors/compute.py
  src/tqec/compile/detectors/compute_test.py
  src/tqec/compile/detectors/database.py
  src/tqec/compile/detectors/database_test.py
  src/tqec/compile/observables.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/enums.py
  src/tqec/plaquette/qubit.py
  src/tqec/plaquette/qubit_test.py
  src/tqec/plaquette/rapng.py
  src/tqec/plaquette/rapng_test.py
  src/tqec/plaquette/rpng.py
  src/tqec/plaquette/rpng_test.py
  src/tqec/scale.py
  src/tqec/templates/__init__.py
  src/tqec/templates/enums.py
  src/tqec/templates/indices/__init__.py
  src/tqec/templates/indices/_testing.py
  src/tqec/templates/indices/_testing_test.py
  src/tqec/templates/indices/base.py
  src/tqec/templates/indices/display.py
  src/tqec/templates/indices/layout.py
  src/tqec/templates/indices/qubit.py
  src/tqec/templates/indices/qubit_test.py
  src/tqec/templates/indices/subtemplates.py
  src/tqec/templates/indices/subtemplates_test.py
  src/tqec/templates/rpng.py
Labels: enhancement, backend, refactor

#422 Start implementing the `RPNGTemplate` library
  src/tqec/compile/specs/enums.py
  src/tqec/plaquette/rpng.py
  src/tqec/plaquette/rpng_test.py
  src/tqec/templates/enums.py
  src/tqec/templates/indices/qubit.py
  src/tqec/templates/indices/qubit_test.py
  src/tqec/templates/indices/subtemplates_test.py
  src/tqec/templates/library/__init__.py
  src/tqec/templates/library/hadamard.py
  src/tqec/templates/library/hadamard_test.py
  src/tqec/templates/library/memory.py
  src/tqec/templates/library/memory_test.py
  src/tqec/templates/library/spatial.py
  src/tqec/templates/library/spatial_test.py
Labels: enhancement, backend

#426 Remove unused code
  src/tqec/__init__.py
  src/tqec/circuit/measurement.py
  src/tqec/circuit/measurement_test.py
  src/tqec/circuit/observable_qubits.py
  src/tqec/circuit/observable_qubits_test.py
  src/tqec/interval.py
  src/tqec/interval_test.py
  src/tqec/plaquette/frozendefaultdict.py
  src/tqec/scale.py
  src/tqec/scale_test.py
  src/tqec/templates/indices/base.py
  src/tqec/templates/rpng.py
Labels: backend

#427 Visualize `RPNGDescription` and `RPNGTemplate`
  .gitignore
  src/tqec/interop/color.py
  src/tqec/plaquette/rpng.py
  src/tqec/plaquette/rpng_test.py
  src/tqec/templates/library/__init__.py
  src/tqec/templates/rpng.py
  src/tqec/templates/viz_rpng.py
Labels: backend

#433 Update contributing guide in docs
  docs/contributor_guide.rst
Labels: documentation, backend

#428 Introduce `RectangularTemplate.get_border_indices` to correctly manage substitutions
  src/tqec/templates/indices/_testing.py
  src/tqec/templates/indices/base.py
  src/tqec/templates/indices/enums.py
  src/tqec/templates/indices/layout.py
  src/tqec/templates/indices/qubit.py
  src/tqec/templates/indices/qubit_test.py
Labels: enhancement, backend
