Repository tqec/tqec, pull requests merged in 2024-01, with the labels that each got.

#44 Implement more QEC experiments
  notebooks/corner.ipynb
  notebooks/extended_logical_qubit.png
  notebooks/logical_qubit_extended_memory_experiment.ipynb
  notebooks/logical_qubit_memory_experiment.ipynb
  src/tqec/noise_models/after_clifford_depolarization.py
  src/tqec/templates/constructions/corner.py
  src/tqec/templates/constructions/qubit.py
Labels: enhancement, help wanted, backend

#69 Frontend fixes and python integration
  README.md
  frontend/.eslintrc.js
  frontend/.gcloudignore
  frontend/.gitignore
  frontend/README.md
  frontend/app.yaml
  frontend/deploy.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/workspace/QubitClass.js
  frontend/src/workspace/TemplateClass.js
  frontend/src/workspace/components/button.js
  frontend/src/workspace/components/notifier.js
  frontend/src/workspace/grid.js
  frontend/src/workspace/index.js
  frontend/src/workspace/plaquettes/Circuit.js
  frontend/src/workspace/plaquettes/PlaquetteClass.js
  frontend/tests/App.test.js
  frontend/tests/setupTests.js
  notebooks/corner.ipynb
  notebooks/logical_qubit_memory_experiment.ipynb
  notebooks/square_plaquette.ipynb
  tqecjs/src/workspace/TileClass.js
Labels: enhancement, help wanted, frontend

#66 Pytest setup
  setup.cfg
  src/tqec/position_test.py
Labels: enhancement, backend, ci/cd

#77 Ricky frontend fixes and python integration
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
Labels: bug

#83 Linting and refactoring
  .gitignore
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/App.jsx
  frontend/src/workspace/QubitClass.js
  frontend/src/workspace/TemplateClass.js
  frontend/src/workspace/components/button.js
  frontend/src/workspace/components/config.js
  frontend/src/workspace/components/downloadButton.js
  frontend/src/workspace/components/notifier.js
  frontend/src/workspace/grid.js
  frontend/src/workspace/index.js
  frontend/src/workspace/plaquettes/PlaquetteClass.js
  src/tqec/static/style.css
  src/tqec/teleportation.stim
  src/tqec/templates/index.html
  web/.gcloudignore
  web/app.yaml
  web/deploy-gcloud.sh
  web/deploy-local.sh
  web/main.py
  web/static/index.html
Labels: bug, enhancement, help wanted, frontend, backend, refactor
