Repository tqec/tqec, pull requests merged in 2025-05, with the labels that each got.

#572 Add more gallery examples
  docs/_static/media/gallery/move_rotation.png
  docs/_static/media/gallery/steane_encoding.png
  docs/_static/media/gallery/three_cnots.png
  docs/conf.py
  docs/gallery/index.rst
  docs/gallery/move_rotation.ipynb
  docs/gallery/steane_encoding.ipynb
  docs/gallery/three_cnots.ipynb
  docs/media/gallery/move_rotation/circuit.stim
  docs/media/gallery/move_rotation/x_move_rotation.png
  docs/media/gallery/move_rotation/z_move_rotation.png
  docs/media/gallery/steane_encoding/circuit.stim
  docs/media/gallery/steane_encoding/steane_encoding_result_X_observable_0.png
  docs/media/gallery/steane_encoding/steane_encoding_result_X_observable_1.png
  docs/media/gallery/steane_encoding/steane_encoding_result_X_observable_2.png
  docs/media/gallery/steane_encoding/steane_encoding_result_Z_observable_0.png
  docs/media/gallery/steane_encoding/steane_encoding_result_Z_observable_1.png
  docs/media/gallery/steane_encoding/steane_encoding_result_Z_observable_2.png
  docs/media/gallery/steane_encoding/steane_encoding_result_Z_observable_3.png
  docs/media/gallery/three_cnots/circuit.stim
  docs/media/gallery/three_cnots/circuit.svg
  docs/media/gallery/three_cnots/three_cnots_result_X_observable_0.png
  docs/media/gallery/three_cnots/three_cnots_result_X_observable_1.png
  docs/media/gallery/three_cnots/three_cnots_result_X_observable_2.png
  docs/media/gallery/three_cnots/three_cnots_result_Z_observable_0.png
  docs/media/gallery/three_cnots/three_cnots_result_Z_observable_1.png
  docs/media/gallery/three_cnots/three_cnots_result_Z_observable_2.png
  pyproject.toml
  src/tqec/gallery/__init__.py
  src/tqec/gallery/dae/steane_encoding.dae
  src/tqec/gallery/steane_encoding.py
  src/tqec/gallery/steane_encoding_test.py
  src/tqec/utils/paths.py
Labels: documentation

#498 Update `architecture.rst`
  docs/architecture.rst
  docs/conf.py
  docs/contributor_guide.rst
  docs/gallery/index.rst
  docs/refs.bib
  docs/user_guide/terminology.rst
  pyproject.toml
Labels: documentation

#581 Fix new errors reported by `mypy` after update
  src/tqec/compile/detectors/compute.py
  src/tqec/compile/generation.py
  src/tqec/compile/tree/annotators/polygons.py
  src/tqec/templates/subtemplates.py
  src/tqec/templates/subtemplates_test.py
  src/tqec/utils/rotations.py
Labels: bug, ci/cd

#593 Add option to show lines missing unit test coverage
  .github/workflows/ci.yml
  pyproject.toml
Labels: ci/cd
