Repository tqec/tqec, pull requests merged in 2025-04, with the labels that each got.

#557 Update meeting link in readme
  README.md
Labels: documentation

#556 Add debug information to `Plaquette`
  src/tqec/compile/tree/tree.py
  src/tqec/plaquette/compilation/base.py
  src/tqec/plaquette/debug.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/rpng/translators/default.py
Labels: enhancement, backend

#558 Implement builders for the fixed-bulk invariant
  src/tqec/__init__.py
  src/tqec/_cli/subcommands/dae2circuits.py
  src/tqec/_cli/subcommands/run_example.py
  src/tqec/compile/__init__.py
  src/tqec/compile/block.py
  src/tqec/compile/compile.py
  src/tqec/compile/compile_test.py
  src/tqec/compile/convention.py
  src/tqec/compile/deprecated/__init__.py
  src/tqec/compile/deprecated/compile.py
  src/tqec/compile/deprecated/compile_test.py
  src/tqec/compile/detectors/compute.py
  src/tqec/compile/detectors/compute_test.py
  src/tqec/compile/detectors/database_test.py
  src/tqec/compile/graph.py
  src/tqec/compile/graph_test.py
  src/tqec/compile/observables/abstract_observable.py
  src/tqec/compile/observables/fixed_bulk_builder.py
  src/tqec/compile/specs/__init__.py
  src/tqec/compile/specs/base.py
  src/tqec/compile/specs/enums.py
  src/tqec/compile/specs/library/__init__.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/compile/specs/library/base.py
  src/tqec/compile/specs/library/css.py
  src/tqec/compile/specs/library/fixed_bulk.py
  src/tqec/compile/specs/library/fixed_parity.py
  src/tqec/compile/specs/library/generators/__init__.py
  src/tqec/compile/specs/library/generators/fixed_bulk.py
  src/tqec/compile/specs/library/generators/fixed_parity.py
  src/tqec/compile/specs/library/generators/hadamard.py
  src/tqec/compile/specs/library/generators/hadamard_test.py
  src/tqec/compile/specs/library/generators/memory.py
  src/tqec/compile/specs/library/generators/memory_test.py
  src/tqec/compile/specs/library/generators/spatial.py
  src/tqec/compile/specs/library/generators/spatial_test.py
  src/tqec/compile/specs/library/standard.py
  src/tqec/compile/specs/library/zxxz.py
  src/tqec/compile/tree/annotators/observables.py
  src/tqec/compile/tree/tree.py
  src/tqec/plaquette/qubit.py
  src/tqec/plaquette/rpng/template.py
  src/tqec/simulation/generation.py
  src/tqec/simulation/simulation.py
  src/tqec/simulation/threshold.py
  src/tqec/templates/enums.py
  src/tqec/templates/qubit.py
  src/tqec/templates/qubit_test.py
  src/tqec/utils/enums.py
Labels: backend

#568 Fix cnot_all_observables.py
  benchmarks/cnot_all_observables.py
Labels: bug

#569 Fix outdated documentation
  docs/gallery/cnot.ipynb
  docs/gallery/memory.ipynb
  docs/media/gallery/cnot/IXIX.png
  docs/media/gallery/cnot/XIXX.png
  docs/media/gallery/cnot/ZIZI.png
  docs/media/gallery/cnot/ZZIZ.png
  docs/media/gallery/cnot/circuit.stim
  docs/media/gallery/logical_cnot/XIXX_circuit.stim
  docs/media/gallery/logical_cnot/simulation/IXIX.png
  docs/media/gallery/logical_cnot/simulation/IZZZ.png
  docs/media/gallery/logical_cnot/simulation/XIXX.png
  docs/media/gallery/logical_cnot/simulation/XXXI.png
  docs/media/gallery/logical_cnot/simulation/ZIZI.png
  docs/media/gallery/logical_cnot/simulation/ZZIZ.png
  docs/media/gallery/memory/circuit.stim
  docs/media/gallery/memory/x_memory.png
  docs/media/gallery/memory/z_memory.png
  docs/user_guide/quick_start.rst
Labels: documentation

#570 Implement `to_json`/`from_json` for `BlockGraph`
  src/tqec/computation/block_graph.py
  src/tqec/computation/block_graph_test.py
  src/tqec/computation/cube.py
  src/tqec/computation/cube_test.py
  src/tqec/computation/pipe.py
  src/tqec/computation/pipe_test.py
  src/tqec/gallery/cnot.py
Labels: enhancement, backend

#567 Temporal logical Hadamard under fixed-bulk convention
  requirements.txt
  src/tqec/compile/compile.py
  src/tqec/compile/compile_test.py
  src/tqec/compile/graph.py
  src/tqec/compile/observables/abstract_observable.py
  src/tqec/compile/observables/abstract_observable_test.py
  src/tqec/compile/observables/builder.py
  src/tqec/compile/observables/fixed_bulk_builder.py
  src/tqec/compile/observables/fixed_bulk_builder_test.py
  src/tqec/compile/observables/fixed_parity_builder.py
  src/tqec/compile/observables/fixed_parity_builder_test.py
  src/tqec/compile/specs/base.py
  src/tqec/compile/specs/library/fixed_bulk.py
  src/tqec/compile/specs/library/generators/fixed_bulk.py
  src/tqec/compile/specs/library/generators/fixed_bulk_test.py
  src/tqec/compile/specs/library/generators/utils.py
  src/tqec/compile/tree/annotations.py
  src/tqec/compile/tree/annotators/observables.py
  src/tqec/compile/tree/annotators/polygons.py
  src/tqec/compile/tree/tree.py
  src/tqec/plaquette/constants.py
  src/tqec/plaquette/debug.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/rpng/__init__.py
  src/tqec/plaquette/rpng/rpng.py
  src/tqec/plaquette/rpng/translators/default.py
  src/tqec/plaquette/rpng/visualisation.py
Labels: enhancement, backend

#531 Introduce BlockGraph.relabel_cubes
  src/tqec/computation/block_graph.py
  src/tqec/computation/block_graph_test.py
Labels: enhancement, backend

#573 Implement detector database transparently
  requirements.txt
  src/tqec/compile/detectors/compute.py
  src/tqec/compile/graph.py
  src/tqec/compile/tree/annotators/detectors.py
  src/tqec/compile/tree/tree.py
  src/tqec/simulation/generation.py
  src/tqec/utils/paths.py
Labels: enhancement
