Repository tqec/tqec, pull requests merged in 2025-01, with the labels that each got.

#431 Plaquette creation and compilation
  src/tqec/circuit/instructions.py
  src/tqec/circuit/moment.py
  src/tqec/circuit/moment_test.py
  src/tqec/circuit/schedule/circuit.py
  src/tqec/plaquette/compilation/base.py
  src/tqec/plaquette/compilation/css.py
  src/tqec/plaquette/compilation/css_test.py
  src/tqec/plaquette/compilation/passes/base.py
  src/tqec/plaquette/compilation/passes/controlled_gate_basis.py
  src/tqec/plaquette/compilation/passes/controlled_gate_basis_test.py
  src/tqec/plaquette/compilation/passes/measurement_basis.py
  src/tqec/plaquette/compilation/passes/measurement_basis_test.py
  src/tqec/plaquette/compilation/passes/reset_basis.py
  src/tqec/plaquette/compilation/passes/reset_basis_test.py
  src/tqec/plaquette/compilation/passes/scheduling.py
  src/tqec/plaquette/compilation/passes/scheduling_test.py
  src/tqec/plaquette/compilation/passes/sort_targets.py
  src/tqec/plaquette/compilation/passes/transformer/__init__.py
  src/tqec/plaquette/compilation/passes/transformer/schedule.py
  src/tqec/plaquette/compilation/passes/transformer/simplifiers.py
  src/tqec/plaquette/compilation/passes/transformer/transformer.py
  src/tqec/plaquette/enums.py
  src/tqec/plaquette/qubit.py
  src/tqec/plaquette/rpng.py
  src/tqec/plaquette/rpng_test.py
  src/tqec/plaquette/translators/base.py
  src/tqec/plaquette/translators/default.py
  src/tqec/plaquette/translators/default_test.py
  src/tqec/templates/library/hadamard.py
  src/tqec/templates/library/hadamard_test.py
  src/tqec/templates/library/memory.py
  src/tqec/templates/library/memory_test.py
  src/tqec/templates/library/spatial.py
  src/tqec/templates/library/spatial_test.py
Labels: enhancement, backend

#442 Add logical CZ gate to gallery
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  src/tqec/computation/_base_graph.py
  src/tqec/computation/block_graph.py
  src/tqec/computation/conversion_test.py
  src/tqec/computation/zx_graph.py
  src/tqec/computation/zx_graph_test.py
  src/tqec/gallery/__init__.py
  src/tqec/gallery/logical_cnot_test.py
  src/tqec/gallery/logical_cz.py
  src/tqec/gallery/logical_cz_test.py
Labels: enhancement, backend

#439 Construct logical observables for spatial junctions
  README.md
  benchmarks/cnot_all_observables.py
  docs/gallery/cnot.ipynb
  docs/gallery/memory.ipynb
  docs/user_guide/quick_start.rst
  examples/logical_cnot.py
  src/tqec/_cli/subcommands/dae2circuits.py
  src/tqec/_cli/subcommands/dae2observables.py
  src/tqec/_cli/subcommands/run_example.py
  src/tqec/compile/compile.py
  src/tqec/compile/compile_test.py
  src/tqec/compile/observables.py
  src/tqec/compile/observables/__init__.py
  src/tqec/compile/observables/abstract_observable.py
  src/tqec/compile/observables/abstract_observable_test.py
  src/tqec/compile/observables/builder.py
  src/tqec/compile/observables/builder_test.py
  src/tqec/compile/specs/enums.py
  src/tqec/computation/abstract_observable.py
  src/tqec/computation/abstract_observable_test.py
  src/tqec/computation/block_graph.py
  src/tqec/computation/correlation.py
  src/tqec/computation/correlation_test.py
  src/tqec/computation/cube.py
  src/tqec/computation/zx_graph.py
  src/tqec/gallery/__init__.py
  src/tqec/gallery/logical_cnot_test.py
  src/tqec/gallery/logical_cz_test.py
  src/tqec/gallery/three_cnots_test.py
  src/tqec/interop/collada/read_write_test.py
  src/tqec/simulation/plotting/inset.py
  src/tqec/simulation/simulation.py
Labels: enhancement, backend, refactor

#443 Generic improvements to the code base
  src/tqec/circuit/moment.py
  src/tqec/circuit/schedule/manipulation.py
  src/tqec/compile/detectors/compute_test.py
  src/tqec/compile/detectors/database_test.py
  src/tqec/compile/specs/base.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/compile/specs/library/css.py
  src/tqec/computation/conversion.py
  src/tqec/computation/cube.py
  src/tqec/computation/cube_test.py
  src/tqec/computation/pipe.py
  src/tqec/computation/pipe_test.py
  src/tqec/enums.py
  src/tqec/enums_test.py
  src/tqec/interop/collada/_correlation.py
  src/tqec/plaquette/__init__.py
  src/tqec/plaquette/compilation/base.py
  src/tqec/plaquette/compilation/css.py
  src/tqec/plaquette/compilation/passes/controlled_gate_basis.py
  src/tqec/plaquette/compilation/passes/controlled_gate_basis_test.py
  src/tqec/plaquette/compilation/passes/measurement_basis.py
  src/tqec/plaquette/compilation/passes/measurement_basis_test.py
  src/tqec/plaquette/compilation/passes/reset_basis.py
  src/tqec/plaquette/compilation/passes/reset_basis_test.py
  src/tqec/plaquette/enums.py
  src/tqec/plaquette/frozendefaultdict.py
  src/tqec/plaquette/library/builder.py
  src/tqec/plaquette/library/css.py
  src/tqec/plaquette/library/css_test.py
  src/tqec/plaquette/library/zxxz.py
  src/tqec/plaquette/library/zxxz_test.py
  src/tqec/plaquette/rpng.py
  src/tqec/plaquette/translators/default.py
  src/tqec/templates/library/hadamard.py
  src/tqec/templates/library/hadamard_test.py
  src/tqec/templates/library/memory.py
  src/tqec/templates/library/memory_test.py
  src/tqec/templates/library/spatial.py
  src/tqec/templates/library/spatial_test.py
  src/tqec/templates/rpng.py
Labels: enhancement, backend

#444 Split template library functions
  src/tqec/templates/library/__init__.py
  src/tqec/templates/library/_testing.py
  src/tqec/templates/library/hadamard.py
  src/tqec/templates/library/hadamard_test.py
  src/tqec/templates/library/memory.py
  src/tqec/templates/library/memory_test.py
  src/tqec/templates/library/spatial.py
  src/tqec/templates/library/spatial_test.py
Labels: enhancement, backend

#447 More gallery computations
  src/tqec/compile/observables/abstract_observable.py
  src/tqec/compile/observables/abstract_observable_test.py
  src/tqec/gallery/__init__.py
  src/tqec/gallery/move_rotation.py
  src/tqec/gallery/move_rotation_test.py
  src/tqec/gallery/solo_node.py
  src/tqec/gallery/solo_node_test.py
Labels: enhancement, backend

#448 Replace most "spatial junction" terms with "spatial cube"
  docs/user_guide/terminology.rst
  src/tqec/compile/observables/abstract_observable.py
  src/tqec/compile/observables/abstract_observable_test.py
  src/tqec/compile/observables/builder.py
  src/tqec/compile/observables/builder_test.py
  src/tqec/compile/specs/base.py
  src/tqec/compile/specs/enums.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/computation/cube.py
  src/tqec/computation/cube_test.py
  src/tqec/templates/indices/__init__.py
  src/tqec/templates/indices/qubit.py
  src/tqec/templates/indices/qubit_test.py
  src/tqec/templates/indices/subtemplates_test.py
  src/tqec/templates/library/_testing.py
  src/tqec/templates/library/memory.py
  src/tqec/templates/library/spatial.py
  src/tqec/templates/library/spatial_test.py
Labels: backend, refactor

#452 Fix duplicate correlation surfaces
  src/tqec/computation/correlation.py
  src/tqec/computation/correlation_test.py
Labels: bug, backend

#451 Write sinter results to file
  src/tqec/simulation/io_utils/__init__.py
  src/tqec/simulation/io_utils/csv_files.py
  src/tqec/simulation/io_utils/csv_files_test.py
  src/tqec/simulation/simulation.py
Labels: enhancement, backend

#454 Enforce coordinate system for `Position2D`
  src/tqec/__init__.py
  src/tqec/circuit/generation.py
  src/tqec/circuit/measurement.py
  src/tqec/circuit/measurement_test.py
  src/tqec/circuit/qubit.py
  src/tqec/circuit/qubit_test.py
  src/tqec/compile/block.py
  src/tqec/compile/compile.py
  src/tqec/compile/detectors/compute.py
  src/tqec/compile/detectors/compute_test.py
  src/tqec/compile/detectors/database.py
  src/tqec/compile/observables/builder_test.py
  src/tqec/plaquette/plaquette.py
  src/tqec/position.py
  src/tqec/position_test.py
  src/tqec/templates/indices/_testing.py
  src/tqec/templates/indices/base.py
  src/tqec/templates/indices/layout.py
  src/tqec/templates/indices/subtemplates_test.py
  src/tqec/templates/rpng.py
Labels: enhancement, backend, QOL

#455 Add back `F401` for unused imports
  ruff.toml
  src/tqec/__init__.py
  src/tqec/circuit/schedule/manipulation.py
  src/tqec/compile/observables/__init__.py
  src/tqec/plaquette/compilation/passes/controlled_gate_basis_test.py
  src/tqec/plaquette/compilation/passes/scheduling_test.py
  src/tqec/plaquette/qubit.py
  src/tqec/plaquette/rpng_test.py
  src/tqec/position_test.py
  src/tqec/templates/indices/_testing.py
  src/tqec/templates/viz_rpng.py
Labels: enhancement, backend, QOL
