Repository tqec/tqec, pull requests merged in 2025-02, with the labels that each got.

#472 Ensure file is listed correctly in the user guide
  docs/user_guide/index.rst
Labels: bug, documentation

#470 Allow the option to copy code blocks in the documentation
  docs/conf.py
  examples/notebooks/sketchup_model.ipynb
  pyproject.toml
Labels: documentation, enhancement

#465 Support taking PyZX `GraphS` with 3D positions as inputs
  pyproject.toml
  requirements.txt
  src/tqec/interop/__init__.py
  src/tqec/interop/pyzx/__init__.py
  src/tqec/interop/pyzx/_testing.py
  src/tqec/interop/pyzx/positioned.py
  src/tqec/interop/pyzx/positioned_test.py
  src/tqec/interop/pyzx/synthesis/__init__.py
  src/tqec/interop/pyzx/synthesis/positioned.py
  src/tqec/interop/pyzx/synthesis/positioned_test.py
  src/tqec/interop/pyzx/synthesis/strategy.py
  src/tqec/interop/pyzx/utils.py
  src/tqec/interop/pyzx/utils_test.py
Labels: enhancement, backend

#473 Update `api.rst`
  docs/api.rst
  src/tqec/computation/block_graph.py
  src/tqec/gallery/move_rotation.py
Labels: bug, documentation

#477 Shift correlation surface during compilation
  src/tqec/compile/compile.py
  src/tqec/compile/compile_test.py
  src/tqec/computation/block_graph.py
  src/tqec/computation/block_graph_test.py
Labels: bug, backend

#478 Correlation surface makes 90 degree turn in the junction
  src/tqec/interop/collada/_correlation.py
Labels: backend, QOL

#480 fix: close #479
  README.md
  docs/user_guide/quick_start.rst
  src/tqec/compile/specs/base.py
Labels: bug

#468 Rotated imports
  src/tqec/computation/block_graph.py
  src/tqec/interop/collada/read_write.py
  src/tqec/interop/collada/read_write_test.py
  src/tqec/interop/collada/test_files/rotated_cnot.dae
  src/tqec/utils/rotations.py
  src/tqec/utils/rotations_test.py
Labels: enhancement, backend

#481 Implement `rotate` method on block graph
  src/tqec/computation/block_graph.py
  src/tqec/computation/block_graph_test.py
  src/tqec/gallery/cz.py
  src/tqec/interop/collada/read_write_test.py
  src/tqec/utils/rotations.py
  src/tqec/utils/rotations_test.py
Labels: enhancement

#440 docs: add disclaimer about rapid code evolution to README
  README.md
Labels: documentation, enhancement

#485 Better issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/finding_materials_from_recordings.md
Labels: documentation, ci/cd

#483 Removing the frontend
  CONTRIBUTING.md
  ggg_frontend/Makefile
  ggg_frontend/README.md
  ggg_frontend/package-lock.json
  ggg_frontend/package.json
  ggg_frontend/public/favicon.ico
  ggg_frontend/public/index.html
  ggg_frontend/public/logo192.png
  ggg_frontend/public/logo512.png
  ggg_frontend/public/manifest.json
  ggg_frontend/public/robots.txt
  ggg_frontend/src/App.css
  ggg_frontend/src/App.js
  ggg_frontend/src/App.test.js
  ggg_frontend/src/code/index.js
  ggg_frontend/src/code/plaquette-type.js
  ggg_frontend/src/constants.js
  ggg_frontend/src/formattedInfoTab.js
  ggg_frontend/src/index.css
  ggg_frontend/src/index.js
  ggg_frontend/src/library/button.js
  ggg_frontend/src/library/circuit.js
  ggg_frontend/src/library/grid.js
  ggg_frontend/src/library/index.js
  ggg_frontend/src/library/plaquette.js
  ggg_frontend/src/library/position.js
  ggg_frontend/src/library/qubit.js
  ggg_frontend/src/library/utils.js
  ggg_frontend/src/reportWebVitals.js
  ggg_frontend/src/setupTests.js
  ggg_frontend/src/tqec_logo.svg
  package-lock.json
Labels: backend

#486 Create a specs library
  src/tqec/compile/specs/library/generators/__init__.py
  src/tqec/compile/specs/library/generators/_testing.py
  src/tqec/compile/specs/library/generators/hadamard.py
  src/tqec/compile/specs/library/generators/hadamard_test.py
  src/tqec/compile/specs/library/generators/memory.py
  src/tqec/compile/specs/library/generators/memory_test.py
  src/tqec/compile/specs/library/generators/spatial.py
  src/tqec/compile/specs/library/generators/spatial_test.py
  src/tqec/compile/specs/library/generators/utils.py
  src/tqec/plaquette/rpng/rpng.py
  src/tqec/templates/library/__init__.py
  src/tqec/templates/library/_testing.py
Labels: enhancement, backend, refactor

#488 Implement Plaquette for spatial junctions
  .gitignore
  src/tqec/plaquette/library/spatial.py
  src/tqec/plaquette/library/spatial_test.py
Labels: backend
