Repository tqec/tqec, pull requests merged in 2025-03, with the labels that each got.

#492 Add cube/pipe naming convention
  docs/media/user_guide/terminology/axes_convention.png
  docs/user_guide/terminology.rst
  src/tqec/__init__.py
  src/tqec/computation/__init__.py
  src/tqec/computation/block_graph.py
  src/tqec/computation/cube.py
  src/tqec/interop/collada/_correlation.py
  src/tqec/interop/collada/_geometry.py
  src/tqec/interop/collada/read_write.py
  src/tqec/interop/pyzx/synthesis/positioned.py
  src/tqec/interop/pyzx/utils.py
  src/tqec/interop/pyzx/utils_test.py
Labels: documentation, enhancement, backend

#495 Minor docstring fix
  src/tqec/plaquette/library/__init__.py
  src/tqec/plaquette/rpng/rpng.py
Labels: documentation

#505 Doc/fix missing import position3 d
  docs/user_guide/build_computations.ipynb
Labels: bug, documentation, backend

#511 Fix shadowed faces to match pipe color
  src/tqec/computation/block_graph.py
  src/tqec/computation/cube.py
  src/tqec/interop/collada/read_write.py
  src/tqec/interop/collada/read_write_test.py
Labels: enhancement

#519 Get cubes by label
  src/tqec/computation/block_graph.py
Labels: enhancement

#503 Representing computation as a tree, detectors and observables are annotations
  src/tqec/circuit/qubit_map.py
  src/tqec/circuit/qubit_map_test.py
  src/tqec/circuit/schedule/manipulation.py
  src/tqec/circuit/schedule/manipulation_test.py
  src/tqec/compile/blocks/block_test.py
  src/tqec/compile/blocks/layers/atomic/layout.py
  src/tqec/compile/blocks/layers/atomic/layout_test.py
  src/tqec/compile/blocks/layers/composed/sequenced.py
  src/tqec/compile/blocks/layers/composed/sequenced_test.py
  src/tqec/compile/blocks/positioning.py
  src/tqec/compile/blocks/positioning_test.py
  src/tqec/compile/generation_test.py
  src/tqec/compile/graph.py
  src/tqec/compile/tree/__init__.py
  src/tqec/compile/tree/annotations.py
  src/tqec/compile/tree/annotators/__init__.py
  src/tqec/compile/tree/annotators/circuit.py
  src/tqec/compile/tree/node.py
  src/tqec/compile/tree/node_test.py
  src/tqec/compile/tree/tree.py
  src/tqec/plaquette/plaquette.py
  src/tqec/plaquette/rpng/translators/default.py
  src/tqec/templates/layout.py
  src/tqec/utils/position.py
Labels: enhancement, backend, refactor

#513 Using detector database in `start_simulation_using_sinter`
  src/tqec/simulation/generation.py
  src/tqec/simulation/simulation.py
Labels: enhancement, backend

#508 Annotate detectors using the layer approach
  src/tqec/compile/tree/annotations.py
  src/tqec/compile/tree/annotators/detectors.py
  src/tqec/compile/tree/annotators/detectors_test.py
  src/tqec/compile/tree/node.py
  src/tqec/compile/tree/tree.py
  src/tqec/plaquette/compilation/base.py
Labels: enhancement, backend, refactor

#516 Annotate observables using the layer approach
  src/tqec/compile/observables/abstract_observable.py
  src/tqec/compile/observables/builder.py
  src/tqec/compile/observables/builder_test.py
  src/tqec/compile/tree/annotations.py
  src/tqec/compile/tree/annotators/observables.py
  src/tqec/compile/tree/node.py
  src/tqec/compile/tree/tree.py
Labels: enhancement, backend, refactor

#522 Automate ports filling to minimize the number of simulation runs
  src/tqec/computation/block_graph.py
  src/tqec/computation/correlation.py
  src/tqec/computation/correlation_test.py
  src/tqec/computation/open_graph.py
  src/tqec/gallery/cnot_test.py
  src/tqec/gallery/cz_test.py
  src/tqec/gallery/move_rotation_test.py
  src/tqec/gallery/three_cnots_test.py
Labels: enhancement

#530 Implement a few post-processing functions for `stim.Circuit`
  src/tqec/circuit/moment.py
  src/tqec/post_processing/merge.py
  src/tqec/post_processing/merge_test.py
  src/tqec/post_processing/remove.py
  src/tqec/post_processing/remove_test.py
  src/tqec/post_processing/utils/moment.py
Labels: enhancement, backend

#535 Use `default_value` instead of `default_factory` in `FrozenDefaultDict`; close #534
  src/tqec/compile/block.py
  src/tqec/compile/blocks/block_test.py
  src/tqec/compile/blocks/layers/atomic/layout_test.py
  src/tqec/compile/blocks/layers/atomic/plaquettes_test.py
  src/tqec/compile/blocks/layers/composed/repeated_test.py
  src/tqec/compile/blocks/layers/composed/sequenced_test.py
  src/tqec/compile/blocks/layers/merge_test.py
  src/tqec/compile/detectors/compute_test.py
  src/tqec/compile/generation_test.py
  src/tqec/compile/specs/library/_utils.py
  src/tqec/compile/specs/library/generators/hadamard.py
  src/tqec/compile/specs/library/generators/memory.py
  src/tqec/compile/specs/library/generators/spatial.py
  src/tqec/compile/tree/annotators/detectors_test.py
  src/tqec/compile/tree/node_test.py
  src/tqec/plaquette/plaquette.py
  src/tqec/templates/layout.py
  src/tqec/utils/frozendefaultdict.py
Labels: bug, enhancement, backend

#526 Single simulation run for multiple observable statistics
  src/tqec/simulation/__init__.py
  src/tqec/simulation/simulation.py
  src/tqec/simulation/split.py
Labels: enhancement, QOL

#538 Add note about how to import assets
  README.md
Labels: documentation, backend

#537 Add explanations for `-e` option to `pip` when installing
  docs/contributor_guide.rst
Labels: documentation, enhancement

#540 Removing warning when instantiating QubitSpatialCubeTemplate with k=1
  src/tqec/compile/specs/library/generators/spatial_test.py
  src/tqec/templates/qubit.py
  src/tqec/templates/qubit_test.py
Labels: backend

#541 Properly handle shadowed faces
  src/tqec/compile/compile.py
  src/tqec/computation/block_graph.py
  src/tqec/computation/block_graph_test.py
  src/tqec/computation/pipe.py
  src/tqec/computation/pipe_test.py
  src/tqec/interop/collada/read_write.py
  src/tqec/interop/collada/read_write_test.py
  src/tqec/utils/position.py
Labels: enhancement, refactor

#543 Correct space time volume definition
  src/tqec/computation/block_graph.py
  src/tqec/computation/block_graph_test.py
  src/tqec/gallery/cnot_test.py
  src/tqec/gallery/cz_test.py
  src/tqec/gallery/move_rotation_test.py
  src/tqec/gallery/three_cnots_test.py
Labels: refactor

#542 Reduce correlation surfaces to a minimal generating set by default when calling `find_correlation_surfaces`
  src/tqec/compile/compile_test.py
  src/tqec/compile/observables/abstract_observable_test.py
  src/tqec/compile/specs/enums.py
  src/tqec/computation/block_graph.py
  src/tqec/computation/correlation.py
  src/tqec/computation/open_graph.py
  src/tqec/gallery/cnot_test.py
  src/tqec/gallery/cz_test.py
  src/tqec/gallery/three_cnots_test.py
  src/tqec/interop/pyzx/correlation.py
  src/tqec/interop/pyzx/correlation_test.py
Labels: refactor, QOL

#546 Add `plot_threshold_as_inset` function
  docs/user_guide/detailed_plot_memory.png
  docs/user_guide/detailed_plots.ipynb
  docs/user_guide/index.rst
  src/tqec/simulation/plotting/inset.py
Labels: enhancement, backend

#545 Implement threshold-finding algorithm
  src/tqec/simulation/threshold.py
Labels: enhancement, backend

#549 Fix layer approach
  src/tqec/compile/blocks/block.py
  src/tqec/compile/blocks/block_test.py
  src/tqec/compile/blocks/layers/atomic/base.py
  src/tqec/compile/blocks/layers/atomic/layout.py
  src/tqec/compile/blocks/layers/atomic/plaquettes.py
  src/tqec/compile/blocks/layers/atomic/plaquettes_test.py
  src/tqec/compile/blocks/layers/atomic/raw.py
  src/tqec/compile/blocks/layers/composed/base.py
  src/tqec/compile/blocks/layers/composed/repeated.py
  src/tqec/compile/blocks/layers/composed/sequenced.py
  src/tqec/compile/blocks/layers/composed/sequenced_test.py
  src/tqec/compile/blocks/layers/merge_test.py
  src/tqec/compile/blocks/layers/spatial.py
  src/tqec/compile/blocks/layers/temporal.py
  src/tqec/compile/blocks/positioning.py
  src/tqec/compile/graph.py
  src/tqec/compile/graph_test.py
  src/tqec/templates/enums.py
  src/tqec/utils/position.py
Labels: bug, backend

#553 Fix local docs build errors
  docs/Makefile
Labels: documentation
